config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'
  get 'todos/delete'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo_items = Todo.all
  end

  def delete
    Todo.last.delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Todo App
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags


  body
    .navbar.navbar-inverse
      .navbar-inner.container
        a.navbar-brand href="#"
          i.glyphicon.glyphicon-ok
          | Just Did It

    = yield
/    .navbar
/    .navbar-default
/      .navbar-fixed-top
/        .navbar-inner
/          .container
/            a.navbar-brand href="#"
/              i.glyphicon.glyphicon-ok
/              | Just Did It
/    = yield
/
/
/
/<div class="navbar navbar-inverse navbar-fixed-top">
/  <div class = "navbar-inner">
/    <div class = "container">
/      <a class="brand" href = "#"><i class="icon-ok"></i>Just Did It</a></p>
/      </div>
/    </div>
/  <div>

app/views/todos/delete.html.slim
p Todo successfully deleted
=link_to 'Back', todos_index_path

app/views/todos/index.html.slim
title Todo App

.container
  .row
    .span4
      h1 Todo App

      hr

      p All Your Todos here
      .well
        - @todo_items.each do |t|
            li= t.todo_item

=link_to 'Delete Last Todo', todos_delete_path